version: '3.4'

services:
  correcao:
    image: correcao
    build:
      context: correcao
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    env_file:
      - ./correcao/.env
  atividades:
    image: atividades
    build:
      context: atividades
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - ./atividades/.env
